### ISSUE TITLE
Double Metaphone without max_code_length?

### ISSUE THREAD

**Issue by Joeboy** [Dalvany/rphonetic#49]
Hi

I'm noticing that `Metaphone::new` takes a `max_code_length` parameter, with the `default()` method setting it to a fairly short 4. Is there any possibility of making `max_code_length` optional, so keys of arbitrary size can be generated? I would think that's what most people would expect, by default. For myself, it took a while to figure out why rphonetic's metaphones didn't match other metaphone libs.

(also applies to `Metaphone` and maybe elsewhere).

Thanks!

**Comment by Dalvany** [comment]
Hello @Joeboy ,
Thank you for using the library.
I'll sse what I can do to make `max_code_length` optional. Can you give a couple of data (input and expected code) so that I can make some basic unit tests for this ? Because I just port Apache commons-codec and they make this parameter required.
